name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.tgz
        tar -xzf allure-2.25.0.tgz
        sudo mv allure-2.25.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Run Playwright tests
      run: npx playwright test

    - name: Generate Allure Report
      run: |
        mkdir -p allure-report
        allure generate --clean allure-results -o allure-report

    - name: Archive Allure Report
      run: |
        zip -r allure-report.zip allure-report

    - name: Upload Allure Report as artifact
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-report
        path: allure-report.zip
        retention-days: 30

    # OPTIONAL: Deploy to GitHub Pages (requires 'gh-pages' branch and settings)
    # - name: Deploy Allure Report to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   if: github.ref == 'refs/heads/main'
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: allure-report
