name: Playwright Tests with Allure

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v4

    - name: Cache dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.npm
          node_modules
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Install Allure
      run: npm install -g allure-commandline

    - name: Download previous report history
      uses: actions/download-artifact@v4
      with:
        name: allure-history
        path: allure-results/history
      continue-on-error: true

    - name: Run tests
      run: npx playwright test

    - name: Generate Allure report
      run: |
        mkdir -p allure-report
        npx allure generate allure-results --clean -o allure-report
        cp -r allure-results/history allure-report/ || true 

    
    - name: Save report history
      uses: actions/upload-artifact@v4
      with:
        name: allure-history
        path: allure-results/history
        retention-days: 30

    
    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
        retention-days: 3

    
    # - name: Deploy to GitHub Pages
    #   if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./allure-report
    #     keep_files: true  